=== forestfamily4/psoutertale-src/rooms/room.schema.json
{
   "$schema": "http://json-schema.org/draft-07/schema",
   "type": "object",
   "properties": {
      "background": {
         "type": "string"
      },
      "face": {
         "type": "string",
         "enum": [
            "down",
            "left",
            "right",
            "up"
         ]
      },
      "layers": {
         "type": "object",
         "additionalProperties": {
            "type": "array",
            "items": {
               "type": "object",
               "properties": {
                  "attachments": {
                     "type": "array",
                     "items": {
                        "oneOf": [
                           {
                              "type": "object",
                              "required": [
                                 "type"
                              ],
                              "properties": {
                                 "anchor": {
                                    "$ref": "./vector.schema.json"
                                 },
                                 "active": {
                                    "type": "boolean"
                                 },
                                 "filters": {
                                    "type": "array",
                                    "items": {
                                       "type": "string"
                                    }
                                 },
                                 "resources": {
                                    "type": "string"
                                 },
                                 "position": {
                                    "$ref": "./vector.schema.json"
                                 },
                                 "rotation": {
                                    "type": "number"
                                 },
                                 "type": {
                                    "enum": [
                                       "animation"
                                    ]
                                 }
                              }
                           },
                           {
                              "type": "object",
                              "required": [
                                 "type"
                              ],
                              "properties": {
                                 "anchor": {
                                    "$ref": "./vector.schema.json"
                                 },
                                 "active": {
                                    "type": "boolean"
                                 },
                                 "filters": {
                                    "type": "array",
                                    "items": {
                                       "type": "string"
                                    }
                                 },
                                 "frames": {
                                    "type": "array",
                                    "items": {
                                       "type": "string"
                                    }
                                 },
                                 "position": {
                                    "$ref": "./vector.schema.json"
                                 },
                                 "rotation": {
                                    "type": "number"
                                 },
                                 "steps": {
                                    "type": "number"
                                 },
                                 "type": {
                                    "enum": [
                                       "sprite"
                                    ]
                                 }
                              }
                           }
                        ]
                     }
                  },
                  "barriers": {
                     "type": "array",
                     "items": {
                        "type": "object",
                        "properties": {
                           "anchor": {
                              "$ref": "./vector.schema.json"
                           },
                           "position": {
                              "$ref": "./vector.schema.json"
                           },
                           "rotation": {
                              "type": "number"
                           },
                           "size": {
                              "$ref": "./vector.schema.json"
                           }
                        }
                     }
                  },
                  "filters": {
                     "type": "array",
                     "items": {
                        "type": "string"
                     }
                  },
                  "interacts": {
                     "type": "array",
                     "items": {
                        "type": "object",
                        "properties": {
                           "anchor": {
                              "$ref": "./vector.schema.json"
                           },
                           "args": {
                              "type": "array",
                              "items": {
                                 "type": "string"
                              }
                           },
                           "name": {
                              "type": "string"
                           },
                           "position": {
                              "$ref": "./vector.schema.json"
                           },
                           "rotation": {
                              "type": "number"
                           },
                           "size": {
                              "$ref": "./vector.schema.json"
                           }
                        }
                     }
                  },
                  "position": {
                     "$ref": "./vector.schema.json"
                  },
                  "rotation": {
                     "type": "number"
                  },
                  "tags": {
                     "type": "array",
                     "items": {
                        "type": "string"
                     }
                  },
                  "triggers": {
                     "type": "array",
                     "items": {
                        "type": "object",
                        "properties": {
                           "anchor": {
                              "$ref": "./vector.schema.json"
                           },
                           "args": {
                              "type": "array",
                              "items": {
                                 "type": "string"
                              }
                           },
                           "name": {
                              "type": "string"
                           },
                           "position": {
                              "$ref": "./vector.schema.json"
                           },
                           "rotation": {
                              "type": "number"
                           },
                           "size": {
                              "$ref": "./vector.schema.json"
                           }
                        }
                     }
                  }
               }
            }
         }
      },
      "metadata": {
         "type": "object"
      },
      "mixins": {
         "type": "object",
         "additionalProperties": {
            "type": "string"
         }
      },
      "neighbors": {
         "type": "array",
         "items": {
            "type": "string"
         }
      },
      "preload": {
         "type": "array",
         "items": {
            "type": "string"
         }
      },
      "region": {
         "type": "array",
         "minItems": 2,
         "maxItems": 2,
         "items": {
            "$ref": "./vector.schema.json",
            "required": [
               "x",
               "y"
            ]
         }
      },
      "score": {
         "type": "object",
         "properties": {
            "filter": {
               "type": "number"
            },
            "gain": {
               "type": "number"
            },
            "music": {
               "type": "string"
            },
            "rate": {
               "type": "number"
            },
            "reverb": {
               "type": "number"
            }
         }
      },
      "spawn": {
         "$ref": "./vector.schema.json",
         "required": [
            "x",
            "y"
         ]
      }
   }
}

=== forestfamily4/psoutertale-src/rooms/w_alley4.json
{
   "$schema": "./room.schema.json",
   "background": "below",
   "preload": [
      "iocTorielLeftHandhold",
      "iocTorielDown",
      "iocTorielDownTalk",
      "asImpact",
      "iocTorielLeft",
      "iocTorielLeftTalk",
      "iocTorielRight",
      "iocTorielRightTalk",
      "iocTorielUp",
      "iocTorielUpTalk",
      "iocTorielHug",
      "amPrebattle",
      "amToriel",
      "iooSBiodome",
      "iooOSecurityFieldTall",
      "iocTorielMad"
   ],
   "layers": {
      "below": [
         {
            "attachments": [
               {
                  "type": "animation",
                  "resources": "iocTwinklyMain",
                  "anchor": {
                     "x": 0,
                     "y": 1
                  }
               }
            ],
            "tags": [
               "stalker"
            ],
            "position": {
               "x": 320,
               "y": 150
            }
         },
         {
            "barriers": [
               {
                  "position": {
                     "x": 80,
                     "y": 200
                  },
                  "size": {
                     "x": 20,
                     "y": 20
                  }
               },
               {
                  "position": {
                     "x": 260,
                     "y": 320
                  },
                  "size": {
                     "x": 40,
                     "y": 220
                  }
               },
               {
                  "position": {
                     "x": 100,
                     "y": 180
                  },
                  "size": {
                     "x": 20,
                     "y": 20
                  }
               },
               {
                  "position": {
                     "x": 120,
                     "y": 160
                  },
                  "size": {
                     "x": 40,
                     "y": 20
                  }
               },
               {
                  "position": {
                     "x": 160,
                     "y": 140
                  },
                  "size": {
                     "x": 40,
                     "y": 20
                  }
               },
               {
                  "position": {
                     "x": 260,
                     "y": 140
                  },
                  "size": {
                     "x": 40,
                     "y": 20
                  }
               },
               {
                  "position": {
                     "x": 300,
                     "y": 160
                  },
                  "size": {
                     "x": 40,
                     "y": 20
                  }
               },
               {
                  "position": {
                     "x": 340,
                     "y": 180
                  },
                  "size": {
                     "x": 20,
                     "y": 20
                  }
               },
               {
                  "position": {
                     "x": 360,
                     "y": 200
                  },
                  "size": {
                     "x": 20,
                     "y": 20
                  }
               },
               {
                  "position": {
                     "x": 380,
                     "y": 220
                  },
                  "size": {
                     "x": 20,
                     "y": 40
                  }
               },
               {
                  "position": {
                     "x": 360,
                     "y": 260
                  },
                  "size": {
                     "x": 20,
                     "y": 20
                  }
               },
               {
                  "position": {
                     "x": 340,
                     "y": 280
                  },
                  "size": {
                     "x": 20,
                     "y": 20
                  }
               },
               {
                  "position": {
                     "x": 300,
                     "y": 300
                  },
                  "size": {
                     "x": 40,
                     "y": 20
                  }
               },
               {
                  "position": {
                     "x": 200,
                     "y": 320
                  },
                  "size": {
                     "x": -180,
                     "y": 180
                  }
               },
               {
                  "position": {
                     "x": 120,
                     "y": 300
                  },
                  "size": {
                     "x": 40,
                     "y": 20
                  }
               },
               {
                  "position": {
                     "x": 100,
                     "y": 280
                  },
                  "size": {
                     "x": 20,
                     "y": 20
                  }
               },
               {
                  "position": {
                     "x": 260,
                     "y": 540
                  },
                  "size": {
                     "x": -240,
                     "y": 20
                  }
               },
               {
                  "position": {
                     "x": 80,
                     "y": 260
                  },
                  "size": {
                     "x": 20,
                     "y": 20
                  }
               },
               {
                  "position": {
                     "x": 60,
                     "y": 220
                  },
                  "size": {
                     "x": 20,
                     "y": 40
                  }
               }
            ],
            "triggers": [
               {
                  "position": {
                     "x": 116,
                     "y": 500
                  },
                  "size": {
                     "x": 20,
                     "y": 40
                  },
                  "name": "outlands",
                  "args": [
                     "runaway"
                  ]
               }
            ]
         },
         {
            "triggers": [
               {
                  "name": "teleport",
                  "position": {
                     "x": 5,
                     "y": 500
                  },
                  "size": {
                     "x": 20,
                     "y": 40
                  },
                  "args": [
                     "w_alley3",
                     "left",
                     "360",
                     "180"
                  ]
               },
               {
                  "name": "teleport",
                  "position": {
                     "x": 200,
                     "y": 140
                  },
                  "size": {
                     "x": 60,
                     "y": 20
                  },
                  "args": [
                     "w_bridge",
                     "up",
                     "40",
                     "1270"
                  ]
               }
            ]
         }
      ]
   },
   "neighbors": [
      "w_alley3",
      "w_bridge"
   ],
   "region": [
      {
         "x": 180,
         "y": 140
      },
      {
         "x": 260,
         "y": 460
      }
   ]
}

=== forestfamily4/psoutertale-src/rooms/f_lobby.json
{
   "$schema": "./room.schema.json",
   "background": "below",
   "preload": [
      "amFactory",
      "avAlphys",
      "asSigstar2",
      "iooSavePoint",
      "iooSavePointDark"
   ],
   "layers": {
      "below": [
         {
            "barriers": [
               {
                  "position": {
                     "x": 20,
                     "y": 120
                  },
                  "size": {
                     "x": 140,
                     "y": -40
                  }
               },
               {
                  "position": {
                     "x": 160,
                     "y": 80
                  },
                  "size": {
                     "x": 40,
                     "y": -20
                  }
               },
               {
                  "position": {
                     "x": 240,
                     "y": 80
                  },
                  "size": {
                     "x": 40,
                     "y": -20
                  }
               },
               {
                  "position": {
                     "x": 280,
                     "y": 80
                  },
                  "size": {
                     "x": 40,
                     "y": 40
                  }
               },
               {
                  "position": {
                     "x": 320,
                     "y": 120
                  },
                  "size": {
                     "x": 20,
                     "y": 80
                  }
               },
               {
                  "position": {
                     "x": 280,
                     "y": 200
                  },
                  "size": {
                     "x": 40,
                     "y": 40
                  }
               },
               {
                  "position": {
                     "x": 160,
                     "y": 240
                  },
                  "size": {
                     "x": 120,
                     "y": 20
                  }
               },
               {
                  "position": {
                     "x": 160,
                     "y": 200
                  },
                  "size": {
                     "x": -60,
                     "y": 40
                  }
               },
               {
                  "position": {
                     "x": 40,
                     "y": 200
                  },
                  "size": {
                     "x": -20,
                     "y": 20
                  }
               },
               {
                  "position": {
                     "x": 20,
                     "y": 120
                  },
                  "size": {
                     "x": -20,
                     "y": 80
                  }
               }
            ],
            "triggers": [
               {
                  "position": {
                     "x": 200,
                     "y": 80
                  },
                  "size": {
                     "x": 40,
                     "y": -20
                  },
                  "name": "teleport",
                  "args": [
                     "f_entrance",
                     "up",
                     "620",
                     "250"
                  ]
               },
               {
                  "position": {
                     "x": 40,
                     "y": 215
                  },
                  "size": {
                     "x": 60,
                     "y": 20
                  },
                  "name": "teleport",
                  "args": [
                     "f_error",
                     "down",
                     "170",
                     "10"
                  ]
               }
            ],
            "interacts": [
               {
                  "position": {
                     "x": 180,
                     "y": 240
                  },
                  "size": {
                     "x": 80,
                     "y": 20
                  },
                  "name": "trivia",
                  "args": [
                     "f_backsign"
                  ]
               },
               {
                  "position": {
                     "x": 60,
                     "y": 100
                  },
                  "size": {
                     "x": 60,
                     "y": 20
                  },
                  "name": "trivia",
                  "args": [
                     "f_lobbywindow"
                  ]
               }
            ]
         }
      ],
      "main": [
         {
            "attachments": [
               {
                  "active": true,
                  "type": "animation",
                  "anchor": {
                     "x": 0,
                     "y": 0
                  },
                  "resources": "iooSavePoint",
                  "position": {
                     "y": -10,
                     "x": 0
                  }
               }
            ],
            "interacts": [
               {
                  "name": "save",
                  "position": {
                     "x": -10
                  },
                  "size": {
                     "x": 20,
                     "y": -10
                  }
               }
            ],
            "barriers": [
               {
                  "position": {
                     "x": -10
                  },
                  "size": {
                     "x": 20,
                     "y": -10
                  }
               }
            ],
            "position": {
               "x": 40,
               "y": 130
            },
            "tags": [
               "spawn"
            ]
         },
         {
            "tags": [
               "f_echoLobby"
            ],
            "attachments": [
               {
                  "type": "animation",
                  "resources": "iooFEchoflower",
                  "anchor": {
                     "x": 0,
                     "y": 1
                  },
                  "auto": false
               }
            ],
            "position": {
               "x": 260,
               "y": 90
            },
            "barriers": [
               {
                  "size": {
                     "x": -20,
                     "y": -5
                  },
                  "anchor": {
                     "x": 0,
                     "y": -1
                  }
               }
            ],
            "interacts": [
               {
                  "anchor": {
                     "x": 0,
                     "y": -1
                  },
                  "size": {
                     "x": -20,
                     "y": -5
                  },
                  "name": "foundry",
                  "args": [
                     "npc",
                     "f_echoLobby"
                  ]
               }
            ]
         },
         {
            "attachments": [
               {
                  "type": "animation",
                  "resources": "iooFCheesetable",
                  "anchor": {
                     "x": 0,
                     "y": 1
                  },
                  "auto": false
               }
            ],
            "position": {
               "x": 300,
               "y": 168
            },
            "tags": [
               "f_cheesetable"
            ],
            "barriers": [
               {
                  "position": {
                     "x": 0,
                     "y": 0
                  },
                  "anchor": {
                     "x": 0,
                     "y": -1
                  },
                  "size": {
                     "x": 27,
                     "y": -5
                  }
               }
            ],
            "interacts": [
               {
                  "size": {
                     "x": 27,
                     "y": -5
                  },
                  "anchor": {
                     "x": 0,
                     "y": -1
                  },
                  "name": "trivia",
                  "args": [
                     "f_cheesetable"
                  ]
               }
            ]
         },
         {
            "attachments": [
               {
                  "type": "sprite",
                  "frames": [
                     "iooFBoots"
                  ],
                  "position": {
                     "x": 218,
                     "y": 143
                  }
               }
            ],
            "position": {
               "x": -187,
               "y": 6
            },
            "interacts": [
               {
                  "position": {
                     "x": 218,
                     "y": 143
                  },
                  "size": {
                     "x": 18,
                     "y": 17
                  },
                  "name": "foundry",
                  "args": [
                     "boots"
                  ]
               }
            ],
            "tags": [
               "f_booties"
            ]
         }
      ]
   },
   "region": [
      {
         "x": 160,
         "y": 120
      },
      {
         "x": 180,
         "y": 140
      }
   ],
   "score": {
      "music": "factory",
      "gain": 1
   },
   "neighbors": [
      "f_error",
      "f_entrance"
   ]
}

=== forestfamily4/psoutertale-src/rooms/w_coffin.json
{
   "$schema": "./room.schema.json",
   "preload": [
      "amChara",
      "avAsriel",
      "asDoorClose"
   ],
   "background": "below",
   "layers": {
      "below": [
         {
            "position": {
               "y": 20
            },
            "barriers": [
               {
                  "position": {
                     "x": 60,
                     "y": 120
                  },
                  "size": {
                     "x": 20,
                     "y": 20
                  }
               },
               {
                  "position": {
                     "x": 60,
                     "y": 180
                  },
                  "size": {
                     "x": 440,
                     "y": 20
                  }
               },
               {
                  "position": {
                     "x": 40,
                     "y": 140
                  },
                  "size": {
                     "x": 20,
                     "y": 40
                  }
               },
               {
                  "position": {
                     "x": 160,
                     "y": 120
                  },
                  "size": {
                     "x": 340,
                     "y": 20
                  }
               },
               {
                  "position": {
                     "x": 80,
                     "y": 115
                  },
                  "size": {
                     "x": 80,
                     "y": 20
                  }
               }
            ]
         },
         {
            "position": {
               "y": 20
            },
            "triggers": [
               {
                  "name": "teleport",
                  "position": {
                     "x": 495,
                     "y": 140
                  },
                  "size": {
                     "x": 20,
                     "y": 40
                  },
                  "args": [
                     "w_candy",
                     "right",
                     "180",
                     "160"
                  ]
               }
            ],
            "interacts": [
               {
                  "name": "outlands",
                  "position": {
                     "x": 80,
                     "y": 115
                  },
                  "size": {
                     "x": 80,
                     "y": 20
                  },
                  "args": [
                     "coffin"
                  ]
               }
            ]
         }
      ]
   },
   "neighbors": [
      "w_candy"
   ],
   "region": [
      {
         "x": 180,
         "y": 120
      },
      {
         "x": 340,
         "y": 120
      }
   ],
   "metadata": {
      "dark02": true
   },
   "score": {
      "music": "chara",
      "reverb": 0.9
   }
}
