=== forestfamily4/psoutertale-src/rooms/room.schema.json
{
   "$schema": "http://json-schema.org/draft-07/schema",
   "type": "object",
   "properties": {
      "background": {
         "type": "string"
      },
      "face": {
         "type": "string",
         "enum": [
            "down",
            "left",
            "right",
            "up"
         ]
      },
      "layers": {
         "type": "object",
         "additionalProperties": {
            "type": "array",
            "items": {
               "type": "object",
               "properties": {
                  "attachments": {
                     "type": "array",
                     "items": {
                        "oneOf": [
                           {
                              "type": "object",
                              "required": [
                                 "type"
                              ],
                              "properties": {
                                 "anchor": {
                                    "$ref": "./vector.schema.json"
                                 },
                                 "active": {
                                    "type": "boolean"
                                 },
                                 "filters": {
                                    "type": "array",
                                    "items": {
                                       "type": "string"
                                    }
                                 },
                                 "resources": {
                                    "type": "string"
                                 },
                                 "position": {
                                    "$ref": "./vector.schema.json"
                                 },
                                 "rotation": {
                                    "type": "number"
                                 },
                                 "type": {
                                    "enum": [
                                       "animation"
                                    ]
                                 }
                              }
                           },
                           {
                              "type": "object",
                              "required": [
                                 "type"
                              ],
                              "properties": {
                                 "anchor": {
                                    "$ref": "./vector.schema.json"
                                 },
                                 "active": {
                                    "type": "boolean"
                                 },
                                 "filters": {
                                    "type": "array",
                                    "items": {
                                       "type": "string"
                                    }
                                 },
                                 "frames": {
                                    "type": "array",
                                    "items": {
                                       "type": "string"
                                    }
                                 },
                                 "position": {
                                    "$ref": "./vector.schema.json"
                                 },
                                 "rotation": {
                                    "type": "number"
                                 },
                                 "steps": {
                                    "type": "number"
                                 },
                                 "type": {
                                    "enum": [
                                       "sprite"
                                    ]
                                 }
                              }
                           }
                        ]
                     }
                  },
                  "barriers": {
                     "type": "array",
                     "items": {
                        "type": "object",
                        "properties": {
                           "anchor": {
                              "$ref": "./vector.schema.json"
                           },
                           "position": {
                              "$ref": "./vector.schema.json"
                           },
                           "rotation": {
                              "type": "number"
                           },
                           "size": {
                              "$ref": "./vector.schema.json"
                           }
                        }
                     }
                  },
                  "filters": {
                     "type": "array",
                     "items": {
                        "type": "string"
                     }
                  },
                  "interacts": {
                     "type": "array",
                     "items": {
                        "type": "object",
                        "properties": {
                           "anchor": {
                              "$ref": "./vector.schema.json"
                           },
                           "args": {
                              "type": "array",
                              "items": {
                                 "type": "string"
                              }
                           },
                           "name": {
                              "type": "string"
                           },
                           "position": {
                              "$ref": "./vector.schema.json"
                           },
                           "rotation": {
                              "type": "number"
                           },
                           "size": {
                              "$ref": "./vector.schema.json"
                           }
                        }
                     }
                  },
                  "position": {
                     "$ref": "./vector.schema.json"
                  },
                  "rotation": {
                     "type": "number"
                  },
                  "tags": {
                     "type": "array",
                     "items": {
                        "type": "string"
                     }
                  },
                  "triggers": {
                     "type": "array",
                     "items": {
                        "type": "object",
                        "properties": {
                           "anchor": {
                              "$ref": "./vector.schema.json"
                           },
                           "args": {
                              "type": "array",
                              "items": {
                                 "type": "string"
                              }
                           },
                           "name": {
                              "type": "string"
                           },
                           "position": {
                              "$ref": "./vector.schema.json"
                           },
                           "rotation": {
                              "type": "number"
                           },
                           "size": {
                              "$ref": "./vector.schema.json"
                           }
                        }
                     }
                  }
               }
            }
         }
      },
      "metadata": {
         "type": "object"
      },
      "mixins": {
         "type": "object",
         "additionalProperties": {
            "type": "string"
         }
      },
      "neighbors": {
         "type": "array",
         "items": {
            "type": "string"
         }
      },
      "preload": {
         "type": "array",
         "items": {
            "type": "string"
         }
      },
      "region": {
         "type": "array",
         "minItems": 2,
         "maxItems": 2,
         "items": {
            "$ref": "./vector.schema.json",
            "required": [
               "x",
               "y"
            ]
         }
      },
      "score": {
         "type": "object",
         "properties": {
            "filter": {
               "type": "number"
            },
            "gain": {
               "type": "number"
            },
            "music": {
               "type": "string"
            },
            "rate": {
               "type": "number"
            },
            "reverb": {
               "type": "number"
            }
         }
      },
      "spawn": {
         "$ref": "./vector.schema.json",
         "required": [
            "x",
            "y"
         ]
      }
   }
}

=== forestfamily4/psoutertale-src/rooms/c_asgore_asriel.json
{
   "$schema": "./room.schema.json",
   "preload": [
      "asDoorClose",
      "iooCAsgoreAsrielOver",
      "avAlphys",
      "asImpact"
   ],
   "background": "below",
   "layers": {
      "below": [
         {
            "barriers": [
               {
                  "position": {
                     "x": 71,
                     "y": 220
                  },
                  "size": {
                     "x": 128,
                     "y": 20
                  }
               },
               {
                  "position": {
                     "x": 51,
                     "y": 101
                  },
                  "size": {
                     "x": 20,
                     "y": 119
                  }
               },
               {
                  "position": {
                     "x": 250,
                     "y": 101
                  },
                  "size": {
                     "x": 20,
                     "y": 119
                  }
               },
               {
                  "position": {
                     "x": 238,
                     "y": 220
                  },
                  "size": {
                     "x": 12,
                     "y": 20
                  }
               },
               {
                  "position": {
                     "x": 123,
                     "y": 100
                  },
                  "size": {
                     "x": 39,
                     "y": 15
                  }
               },
               {
                  "position": {
                     "x": 169,
                     "y": 100
                  },
                  "size": {
                     "x": 30,
                     "y": 21
                  }
               },
               {
                  "position": {
                     "x": 205,
                     "y": 105
                  },
                  "size": {
                     "x": 32,
                     "y": 51
                  }
               },
               {
                  "position": {
                     "x": 225,
                     "y": 157
                  },
                  "size": {
                     "x": 24,
                     "y": 15
                  }
               },
               {
                  "position": {
                     "x": 70,
                     "y": 101
                  },
                  "size": {
                     "x": 32,
                     "y": 55
                  }
               },
               {
                  "position": {
                     "x": 102,
                     "y": 101
                  },
                  "size": {
                     "x": 21,
                     "y": -20
                  }
               }
            ],
            "interacts": [
               {
                  "position": {
                     "x": 131,
                     "y": 99
                  },
                  "size": {
                     "x": 9,
                     "y": 15
                  },
                  "name": "trivia",
                  "args": [
                     "c_aa_paper"
                  ]
               },
               {
                  "position": {
                     "x": 105,
                     "y": 101
                  },
                  "size": {
                     "x": 16,
                     "y": -20
                  },
                  "name": "trivia",
                  "args": [
                     "c_aa_flower"
                  ]
               },
               {
                  "position": {
                     "x": 168,
                     "y": 100
                  },
                  "size": {
                     "x": 31,
                     "y": 21
                  },
                  "name": "trivia",
                  "args": [
                     "c_aa_cabinet"
                  ]
               },
               {
                  "position": {
                     "x": 225,
                     "y": 158
                  },
                  "size": {
                     "x": 23,
                     "y": 13
                  },
                  "name": "trivia",
                  "args": [
                     "c_aa_box"
                  ]
               },
               {
                  "position": {
                     "x": 148,
                     "y": 100
                  },
                  "size": {
                     "x": 6,
                     "y": 14
                  },
                  "name": "trivia",
                  "args": [
                     "c_aa_frame"
                  ]
               },
               {
                  "position": {
                     "x": 205,
                     "y": 122
                  },
                  "size": {
                     "x": 32,
                     "y": 34
                  },
                  "name": "citadel",
                  "args": [
                     "bed"
                  ]
               },
               {
                  "position": {
                     "x": 71,
                     "y": 105
                  },
                  "size": {
                     "x": 31,
                     "y": 51
                  },
                  "name": "trivia",
                  "args": [
                     "c_aa_deathbed"
                  ]
               }
            ]
         },
         {
            "interacts": [],
            "triggers": [
               {
                  "name": "teleport",
                  "position": {
                     "x": 199,
                     "y": 235
                  },
                  "size": {
                     "x": 39,
                     "y": 20
                  },
                  "args": [
                     "c_asgore_hallway",
                     "down",
                     "170.5",
                     "122"
                  ]
               }
            ]
         },
         {
            "attachments": [
               {
                  "type": "sprite",
                  "frames": [
                     "iooSCrossword"
                  ],
                  "anchor": {
                     "x": 0,
                     "y": 0
                  }
               }
            ],
            "tags": [
               "ultranote"
            ],
            "interacts": [
               {
                  "size": {
                     "x": 20,
                     "y": 20
                  },
                  "anchor": {
                     "x": 0,
                     "y": 0
                  },
                  "name": "trivia",
                  "args": [
                     "ultranote"
                  ]
               }
            ],
            "position": {
               "x": 149,
               "y": 167
            }
         }
      ],
      "main": [
         {
            "attachments": [
               {
                  "type": "animation",
                  "resources": "iooCPresent",
                  "anchor": {
                     "x": 0,
                     "y": 1
                  },
                  "position": {
                     "x": 0,
                     "y": 0
                  }
               }
            ],
            "barriers": [
               {
                  "anchor": {
                     "x": 0,
                     "y": -1
                  },
                  "size": {
                     "x": -20,
                     "y": -12
                  }
               }
            ],
            "position": {
               "x": 126,
               "y": 216
            },
            "tags": [
               "giftbox1"
            ],
            "interacts": [
               {
                  "anchor": {
                     "x": 0,
                     "y": -1
                  },
                  "size": {
                     "x": -20,
                     "y": -12
                  },
                  "name": "citadel",
                  "args": [
                     "giftbox1"
                  ]
               }
            ]
         },
         {
            "attachments": [
               {
                  "type": "animation",
                  "resources": "iooCPresent",
                  "anchor": {
                     "x": 0,
                     "y": 1
                  },
                  "position": {
                     "x": 0,
                     "y": 0
                  }
               }
            ],
            "barriers": [
               {
                  "anchor": {
                     "x": 0,
                     "y": -1
                  },
                  "size": {
                     "x": -20,
                     "y": -12
                  }
               }
            ],
            "position": {
               "x": 172,
               "y": 216
            },
            "tags": [
               "giftbox2"
            ],
            "interacts": [
               {
                  "anchor": {
                     "x": 0,
                     "y": -1
                  },
                  "size": {
                     "x": -20,
                     "y": -12
                  },
                  "name": "citadel",
                  "args": [
                     "giftbox2"
                  ]
               }
            ]
         }
      ]
   },
   "neighbors": [
      "c_asgore_hallway"
   ],
   "region": [
      {
         "x": 160,
         "y": 120.5
      },
      {
         "x": 160,
         "y": 120.5
      }
   ]
}

=== forestfamily4/psoutertale-src/rooms/a_core_entry1.json
{
   "$schema": "./room.schema.json",
   "background": "below",
   "layers": {
      "below": [
         {
            "barriers": [
               {
                  "position": {
                     "x": 80,
                     "y": 0
                  },
                  "size": {
                     "x": 220,
                     "y": 520
                  }
               },
               {
                  "position": {
                     "x": 20,
                     "y": 520
                  },
                  "size": {
                     "x": 20,
                     "y": -20
                  }
               },
               {
                  "position": {
                     "x": 0,
                     "y": 520
                  },
                  "size": {
                     "x": 20,
                     "y": 40
                  }
               },
               {
                  "position": {
                     "x": 380,
                     "y": 0
                  },
                  "size": {
                     "x": 20,
                     "y": 560
                  }
               },
               {
                  "position": {
                     "x": 20,
                     "y": 560
                  },
                  "size": {
                     "x": 360,
                     "y": 20
                  }
               }
            ],
            "triggers": [
               {
                  "position": {
                     "x": 40,
                     "y": 520
                  },
                  "size": {
                     "x": 40,
                     "y": -20
                  },
                  "name": "teleport",
                  "args": [
                     "a_citadelevator",
                     "up",
                     "160",
                     "230"
                  ]
               },
               {
                  "position": {
                     "x": 300,
                     "y": 5
                  },
                  "size": {
                     "x": 80,
                     "y": -20
                  },
                  "name": "teleport",
                  "args": [
                     "a_core_entry2",
                     "up",
                     "160",
                     "510"
                  ]
               }
            ],
            "attachments": [
               {
                  "type": "animation",
                  "resources": "iooACorecolumn",
                  "active": true,
                  "anchor": {
                     "x": 0,
                     "y": -1
                  },
                  "position": {
                     "x": 270,
                     "y": 460
                  }
               },
               {
                  "type": "animation",
                  "resources": "iooACorecolumn",
                  "active": true,
                  "anchor": {
                     "x": 0,
                     "y": -1
                  },
                  "position": {
                     "x": 230,
                     "y": 460
                  }
               }
            ],
            "interacts": [
               {
                  "position": {
                     "x": 160,
                     "y": 500
                  },
                  "size": {
                     "x": 40,
                     "y": 20
                  },
                  "name": "trivia",
                  "args": [
                     "coresign1"
                  ]
               }
            ]
         },
         {
            "tags": [
               "hexfloor"
            ],
            "interacts": [
               {
                  "position": {
                     "x": 300,
                     "y": 0
                  },
                  "size": {
                     "x": 80,
                     "y": 560
                  }
               },
               {
                  "position": {
                     "x": 20,
                     "y": 520
                  },
                  "size": {
                     "x": 280,
                     "y": 40
                  }
               }
            ]
         }
      ],
      "main": [
         {
            "attachments": [
               {
                  "active": true,
                  "type": "animation",
                  "anchor": {
                     "x": 0,
                     "y": 0
                  },
                  "resources": "iooSavePoint",
                  "position": {
                     "y": -10,
                     "x": 0
                  }
               }
            ],
            "interacts": [
               {
                  "name": "save",
                  "position": {
                     "x": -10
                  },
                  "size": {
                     "x": 20,
                     "y": -10
                  }
               }
            ],
            "barriers": [
               {
                  "position": {
                     "x": -10
                  },
                  "size": {
                     "x": 20,
                     "y": -10
                  }
               }
            ],
            "position": {
               "x": 100,
               "y": 530
            },
            "tags": [
               "spawn"
            ]
         }
      ]
   },
   "preload": [
      "amCore",
      "amYouscreweduppal",
      "#aerialis-b-dark",
      "avAlphys",
      "idcAlphys",
      "ionADarkman",
      "iooAFloorsegment",
      "asShatter"
   ],
   "score": {
      "music": "CORE",
      "gain": 1
   },
   "neighbors": [
      "a_citadelevator",
      "a_core_entry2"
   ],
   "region": [
      {
         "x": 160,
         "y": 120
      },
      {
         "x": 340,
         "y": 460
      }
   ]
}
