=== forestfamily4/psoutertale-src/rooms/room.schema.json
{
   "$schema": "http://json-schema.org/draft-07/schema",
   "type": "object",
   "properties": {
      "background": {
         "type": "string"
      },
      "face": {
         "type": "string",
         "enum": [
            "down",
            "left",
            "right",
            "up"
         ]
      },
      "layers": {
         "type": "object",
         "additionalProperties": {
            "type": "array",
            "items": {
               "type": "object",
               "properties": {
                  "attachments": {
                     "type": "array",
                     "items": {
                        "oneOf": [
                           {
                              "type": "object",
                              "required": [
                                 "type"
                              ],
                              "properties": {
                                 "anchor": {
                                    "$ref": "./vector.schema.json"
                                 },
                                 "active": {
                                    "type": "boolean"
                                 },
                                 "filters": {
                                    "type": "array",
                                    "items": {
                                       "type": "string"
                                    }
                                 },
                                 "resources": {
                                    "type": "string"
                                 },
                                 "position": {
                                    "$ref": "./vector.schema.json"
                                 },
                                 "rotation": {
                                    "type": "number"
                                 },
                                 "type": {
                                    "enum": [
                                       "animation"
                                    ]
                                 }
                              }
                           },
                           {
                              "type": "object",
                              "required": [
                                 "type"
                              ],
                              "properties": {
                                 "anchor": {
                                    "$ref": "./vector.schema.json"
                                 },
                                 "active": {
                                    "type": "boolean"
                                 },
                                 "filters": {
                                    "type": "array",
                                    "items": {
                                       "type": "string"
                                    }
                                 },
                                 "frames": {
                                    "type": "array",
                                    "items": {
                                       "type": "string"
                                    }
                                 },
                                 "position": {
                                    "$ref": "./vector.schema.json"
                                 },
                                 "rotation": {
                                    "type": "number"
                                 },
                                 "steps": {
                                    "type": "number"
                                 },
                                 "type": {
                                    "enum": [
                                       "sprite"
                                    ]
                                 }
                              }
                           }
                        ]
                     }
                  },
                  "barriers": {
                     "type": "array",
                     "items": {
                        "type": "object",
                        "properties": {
                           "anchor": {
                              "$ref": "./vector.schema.json"
                           },
                           "position": {
                              "$ref": "./vector.schema.json"
                           },
                           "rotation": {
                              "type": "number"
                           },
                           "size": {
                              "$ref": "./vector.schema.json"
                           }
                        }
                     }
                  },
                  "filters": {
                     "type": "array",
                     "items": {
                        "type": "string"
                     }
                  },
                  "interacts": {
                     "type": "array",
                     "items": {
                        "type": "object",
                        "properties": {
                           "anchor": {
                              "$ref": "./vector.schema.json"
                           },
                           "args": {
                              "type": "array",
                              "items": {
                                 "type": "string"
                              }
                           },
                           "name": {
                              "type": "string"
                           },
                           "position": {
                              "$ref": "./vector.schema.json"
                           },
                           "rotation": {
                              "type": "number"
                           },
                           "size": {
                              "$ref": "./vector.schema.json"
                           }
                        }
                     }
                  },
                  "position": {
                     "$ref": "./vector.schema.json"
                  },
                  "rotation": {
                     "type": "number"
                  },
                  "tags": {
                     "type": "array",
                     "items": {
                        "type": "string"
                     }
                  },
                  "triggers": {
                     "type": "array",
                     "items": {
                        "type": "object",
                        "properties": {
                           "anchor": {
                              "$ref": "./vector.schema.json"
                           },
                           "args": {
                              "type": "array",
                              "items": {
                                 "type": "string"
                              }
                           },
                           "name": {
                              "type": "string"
                           },
                           "position": {
                              "$ref": "./vector.schema.json"
                           },
                           "rotation": {
                              "type": "number"
                           },
                           "size": {
                              "$ref": "./vector.schema.json"
                           }
                        }
                     }
                  }
               }
            }
         }
      },
      "metadata": {
         "type": "object"
      },
      "mixins": {
         "type": "object",
         "additionalProperties": {
            "type": "string"
         }
      },
      "neighbors": {
         "type": "array",
         "items": {
            "type": "string"
         }
      },
      "preload": {
         "type": "array",
         "items": {
            "type": "string"
         }
      },
      "region": {
         "type": "array",
         "minItems": 2,
         "maxItems": 2,
         "items": {
            "$ref": "./vector.schema.json",
            "required": [
               "x",
               "y"
            ]
         }
      },
      "score": {
         "type": "object",
         "properties": {
            "filter": {
               "type": "number"
            },
            "gain": {
               "type": "number"
            },
            "music": {
               "type": "string"
            },
            "rate": {
               "type": "number"
            },
            "reverb": {
               "type": "number"
            }
         }
      },
      "spawn": {
         "$ref": "./vector.schema.json",
         "required": [
            "x",
            "y"
         ]
      }
   }
}

=== forestfamily4/psoutertale-src/rooms/f_shyren.json
{
   "$schema": "./room.schema.json",
   "background": "below",
   "preload": [
      "amGenerator",
      "iooFSteam"
   ],
   "layers": {
      "below": [
         {
            "position": {
               "x": 0,
               "y": 0
            },
            "barriers": [
               {
                  "position": {
                     "x": 0,
                     "y": 60
                  },
                  "size": {
                     "x": 20,
                     "y": 60
                  }
               },
               {
                  "position": {
                     "x": 20,
                     "y": 80
                  },
                  "size": {
                     "x": 100,
                     "y": -20
                  }
               },
               {
                  "position": {
                     "x": 200,
                     "y": 60
                  },
                  "size": {
                     "x": 100,
                     "y": 20
                  }
               },
               {
                  "position": {
                     "x": 0,
                     "y": 180
                  },
                  "size": {
                     "x": 20,
                     "y": 40
                  }
               },
               {
                  "position": {
                     "x": 20,
                     "y": 220
                  },
                  "size": {
                     "x": 100,
                     "y": 20
                  }
               },
               {
                  "position": {
                     "x": 200,
                     "y": 220
                  },
                  "size": {
                     "x": 100,
                     "y": 20
                  }
               },
               {
                  "position": {
                     "x": 300,
                     "y": 80
                  },
                  "size": {
                     "x": 20,
                     "y": 40
                  }
               },
               {
                  "position": {
                     "x": 300,
                     "y": 180
                  },
                  "size": {
                     "x": 20,
                     "y": 40
                  }
               }
            ],
            "triggers": [
               {
                  "position": {
                     "x": 5,
                     "y": 120
                  },
                  "size": {
                     "x": -20,
                     "y": 60
                  },
                  "name": "teleport",
                  "args": [
                     "f_muffet",
                     "left",
                     "1020",
                     "170"
                  ]
               },
               {
                  "position": {
                     "x": 120,
                     "y": 80
                  },
                  "size": {
                     "x": 80,
                     "y": -20
                  },
                  "name": "teleport",
                  "args": [
                     "f_piano",
                     "up",
                     "160",
                     "230"
                  ]
               },
               {
                  "position": {
                     "x": 120,
                     "y": 235
                  },
                  "size": {
                     "x": 80,
                     "y": 20
                  },
                  "name": "teleport",
                  "args": [
                     "f_statue",
                     "down",
                     "200",
                     "90"
                  ]
               },
               {
                  "position": {
                     "x": 315,
                     "y": 120
                  },
                  "size": {
                     "x": 20,
                     "y": 60
                  },
                  "name": "teleport",
                  "args": [
                     "f_path",
                     "right",
                     "20",
                     "410"
                  ]
               }
            ]
         },
         {
            "tags": [
               "steamgap"
            ],
            "interacts": [
               {
                  "position": {
                     "x": 140,
                     "y": 100
                  },
                  "size": {
                     "x": 40,
                     "y": 100
                  }
               },
               {
                  "position": {
                     "x": 120,
                     "y": 120
                  },
                  "size": {
                     "x": 80,
                     "y": 60
                  }
               }
            ]
         }
      ],
      "main": [
         {
            "attachments": [
               {
                  "active": true,
                  "type": "animation",
                  "anchor": {
                     "x": 0,
                     "y": 0
                  },
                  "resources": "iooSavePoint",
                  "position": {
                     "x": 0,
                     "y": -10
                  }
               }
            ],
            "interacts": [
               {
                  "name": "save",
                  "position": {
                     "x": -10
                  },
                  "size": {
                     "x": 20,
                     "y": -10
                  }
               }
            ],
            "barriers": [
               {
                  "position": {
                     "x": -10
                  },
                  "size": {
                     "x": 20,
                     "y": -10
                  }
               }
            ],
            "position": {
               "x": 115,
               "y": 90
            },
            "tags": [
               "spawn"
            ]
         },
         {
            "tags": [
               "vending_machine"
            ],
            "position": {
               "x": 66,
               "y": 90
            },
            "attachments": [
               {
                  "type": "animation",
                  "active": true,
                  "resources": "iooFVendingMachine",
                  "anchor": {
                     "y": 1
                  }
               }
            ],
            "barriers": [
               {
                  "size": {
                     "y": -13,
                     "x": 28
                  }
               }
            ],
            "interacts": [
               {
                  "name": "foundry",
                  "size": {
                     "y": -13,
                     "x": 28
                  },
                  "args": [
                     "candy"
                  ]
               }
            ]
         },
         {
            "tags": [
               "dimbox"
            ],
            "attachments": [
               {
                  "type": "animation",
                  "resources": "iooDimbox",
                  "position": {
                     "x": 0,
                     "y": 0
                  },
                  "anchor": {
                     "x": 0,
                     "y": 1
                  }
               }
            ],
            "position": {
               "x": 240,
               "y": 90
            },
            "barriers": [
               {
                  "anchor": {
                     "x": 0,
                     "y": 1
                  },
                  "position": {
                     "x": 0,
                     "y": 0
                  },
                  "size": {
                     "x": -20,
                     "y": 9
                  }
               }
            ],
            "interacts": [
               {
                  "anchor": {
                     "x": 0,
                     "y": 1
                  },
                  "size": {
                     "x": -20,
                     "y": 9
                  },
                  "name": "starton",
                  "args": [
                     "dimbox"
                  ]
               }
            ]
         },
         {
            "attachments": [
               {
                  "type": "sprite",
                  "frames": [
                     "iooFSign"
                  ],
                  "anchor": {
                     "x": 0,
                     "y": 1
                  },
                  "position": {
                     "x": 0,
                     "y": 0
                  }
               }
            ],
            "barriers": [
               {
                  "anchor": {
                     "x": 0,
                     "y": -1
                  },
                  "size": {
                     "x": -20,
                     "y": -5
                  }
               }
            ],
            "position": {
               "x": 215,
               "y": 91
            },
            "interacts": [
               {
                  "anchor": {
                     "x": 0,
                     "y": 1
                  },
                  "size": {
                     "x": 20,
                     "y": 5
                  },
                  "name": "trivia",
                  "args": [
                     "f_doge_sign"
                  ]
               }
            ]
         }
      ]
   },
   "region": [
      {
         "x": 160,
         "y": 120
      },
      {
         "x": 160,
         "y": 120
      }
   ],
   "score": {
      "music": "generator",
      "gain": 1
   },
   "neighbors": [
      "f_piano",
      "f_path",
      "f_statue",
      "f_muffet"
   ]
}

=== forestfamily4/psoutertale-src/rooms/a_auditorium.json
{
   "$schema": "./room.schema.json",
   "background": "below",
   "metadata": {
      "dark03": true
   },
   "preload": [
      "amMall",
      "amYouscreweduppal",
      "#aerialis-b-dark",
      "iooAShowglow",
      "amOpera",
      "amOperaAlt",
      "asBad",
      "iocMettatonDressPull",
      "iocMettatonDressIdle",
      "iocMettatonDressRoll",
      "idcAlphys",
      "avAlphys",
      "iocAlphys",
      "avMettaton",
      "asBoom",
      "iooASakuraLeaf",
      "iocMettaton",
      "iocMettatonShrug",
      "asCymbal",
      "iooADeadLeaf",
      "iocAsrielEarTugWater",
      "iocAsrielEarTug"
   ],
   "layers": {
      "below": [
         {
            "barriers": [
               {
                  "position": {
                     "x": 0,
                     "y": 200
                  },
                  "size": {
                     "x": 80,
                     "y": -20
                  }
               },
               {
                  "position": {
                     "x": 80,
                     "y": 180
                  },
                  "size": {
                     "x": 320,
                     "y": -20
                  }
               },
               {
                  "position": {
                     "x": 400,
                     "y": 180
                  },
                  "size": {
                     "x": 80,
                     "y": 20
                  }
               },
               {
                  "position": {
                     "x": 480,
                     "y": 280
                  },
                  "size": {
                     "x": -480,
                     "y": 20
                  }
               }
            ],
            "triggers": [
               {
                  "position": {
                     "x": -15,
                     "y": 200
                  },
                  "size": {
                     "x": 20,
                     "y": 80
                  },
                  "name": "teleport",
                  "args": [
                     "a_elevator4",
                     "left",
                     "340",
                     "260"
                  ]
               },
               {
                  "position": {
                     "x": 475,
                     "y": 200
                  },
                  "size": {
                     "x": 20,
                     "y": 80
                  },
                  "name": "teleport",
                  "args": [
                     "a_aftershow",
                     "right",
                     "20",
                     "160"
                  ]
               }
            ],
            "position": {
               "x": 0,
               "y": -60
            },
            "attachments": [
               {
                  "type": "animation",
                  "resources": "iooAReccolumn",
                  "active": true,
                  "anchor": {
                     "x": 0,
                     "y": -1
                  },
                  "position": {
                     "x": 450,
                     "y": 120
                  }
               },
               {
                  "type": "animation",
                  "resources": "iooAReccolumn",
                  "active": true,
                  "anchor": {
                     "x": 0,
                     "y": -1
                  },
                  "position": {
                     "x": 30,
                     "y": 120
                  }
               }
            ]
         }
      ]
   },
   "score": {
      "music": "mall",
      "gain": 1
   },
   "neighbors": [
      "a_elevator4",
      "a_aftershow"
   ],
   "region": [
      {
         "x": 160,
         "y": 140
      },
      {
         "x": 320,
         "y": 140
      }
   ]
}
